---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: docker.io/mattjmcnaughton/blog:e92036b62bf9228440ad19bcf243fb9f4f6e52f9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  labels:
    app: blog
spec:
  type: LoadBalancer
  selector:
    app: blog
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
